-- RestaurantMom demo seed data. Fictional restaurants on purpose: the repo is public,
-- so no fake bad reviews of real places.
--
-- RESETS the demo data: truncates restaurants and dishes (and restarts their ids), then
-- reloads everything below. chat_state is left alone. Safe to run repeatedly.
-- Run with: npm run db:seed   (or paste into the Neon SQL editor)

TRUNCATE dishes, restaurants RESTART IDENTITY CASCADE;

INSERT INTO restaurants (name, neighborhood, city) VALUES
  ('Harrison Street Deli', 'SoMa', 'San Francisco'),
  ('Golden Gate Grill', 'Inner Richmond', 'San Francisco'),
  ('Mission Taqueria Luz', 'Mission', 'San Francisco'),
  ('Bayou on Valencia', 'Mission', 'San Francisco'),
  ('Fog City Fish & Chips', 'Outer Sunset', 'San Francisco'),
  ('Noodle Cable Car', 'Chinatown', 'San Francisco'),
  ('Bernal Heights Barbecue Co.', 'Bernal Heights', 'San Francisco'),
  ('Little Lotus Thai', 'Tenderloin', 'San Francisco'),
  ('The Salty Anchor', 'Embarcadero', 'San Francisco'),
  ('Dolores Park Pizzeria', 'Mission', 'San Francisco'),
  ('Sunset Sushi Studio', 'Inner Sunset', 'San Francisco'),
  ('Calle Fuego', 'Mission', 'San Francisco'),
  ('Nob Hill Steakhouse', 'Nob Hill', 'San Francisco'),
  ('Presidio Picnic Cafe', 'Presidio', 'San Francisco'),
  ('Marina Brunch Club', 'Marina', 'San Francisco'),
  ('Hayes Valley Ramen Bar', 'Hayes Valley', 'San Francisco');

INSERT INTO dishes (restaurant_id, dish, rating, would_order_again, note, tags, eaten_on) VALUES
  ((SELECT id FROM restaurants WHERE name = 'Harrison Street Deli'), 'French dip', 1, false, 'Roll turned to wet cardboard in the jus. Beef was gray and thin.', ARRAY['soggy', 'bland']::text[], '2026-03-14'),
  ((SELECT id FROM restaurants WHERE name = 'Harrison Street Deli'), 'Pastrami on rye', 5, true, 'Thick-cut, peppery bark, rye held up. Get this.', ARRAY['peppery', 'hearty']::text[], '2026-05-02'),
  ((SELECT id FROM restaurants WHERE name = 'Golden Gate Grill'), 'French dip', 2, false, 'Better than the deli but bread still collapsed. Jus was salty.', ARRAY['soggy', 'salty']::text[], '2026-06-20'),
  ((SELECT id FROM restaurants WHERE name = 'Golden Gate Grill'), 'Smash burger', 4, true, 'Crispy edges, good char. Fries were limp though.', ARRAY['crispy']::text[], '2026-06-20'),
  ((SELECT id FROM restaurants WHERE name = 'Mission Taqueria Luz'), 'Carnitas burrito', 5, true, 'Crispy carnitas, great salsa verde.', ARRAY['crispy', 'spicy']::text[], '2026-07-08'),
  ((SELECT id FROM restaurants WHERE name = 'Mission Taqueria Luz'), 'Fish tacos', 2, false, 'Batter went soft fast, fish was mushy.', ARRAY['soggy']::text[], '2026-08-15'),
  ((SELECT id FROM restaurants WHERE name = 'Bayou on Valencia'), 'Shrimp po''boy', 2, false, 'Not real Leidenheimer-style bread, too soft. Remoulade bland.', ARRAY['soggy', 'bland']::text[], '2026-09-05'),
  ((SELECT id FROM restaurants WHERE name = 'Bayou on Valencia'), 'Gumbo', 4, true, 'Dark roux, good andouille. Close to home.', ARRAY['smoky', 'hearty']::text[], '2026-09-05'),
  ((SELECT id FROM restaurants WHERE name = 'Mission Taqueria Luz'), 'al pastor', 4, true, 'nice char', ARRAY['charred']::text[], '2026-10-04'),
  ((SELECT id FROM restaurants WHERE name = 'Mission Taqueria Luz'), 'Carne asada', 4, true, 'nice char', ARRAY['charred']::text[], '2026-10-04'),
  ((SELECT id FROM restaurants WHERE name = 'Bayou on Valencia'), 'shrimp po'' boy', 3, false, 'bread was a little soggy', ARRAY['soggy']::text[], '2026-10-04'),
  ((SELECT id FROM restaurants WHERE name = 'Harrison Street Deli'), 'Reuben', 3, false, 'Good corned beef but the kraut made the rye soggy halfway through.', ARRAY['soggy', 'tangy']::text[], '2026-08-11'),
  ((SELECT id FROM restaurants WHERE name = 'Harrison Street Deli'), 'Turkey club', 2, false, 'Dry turkey, bland, no crunch on the bacon.', ARRAY['bland', 'dry']::text[], '2026-09-02'),
  ((SELECT id FROM restaurants WHERE name = 'Golden Gate Grill'), 'Patty melt', 4, true, 'Crisp griddled rye, onions properly charred.', ARRAY['crispy', 'charred']::text[], '2026-09-14'),
  ((SELECT id FROM restaurants WHERE name = 'Golden Gate Grill'), 'Onion rings', 2, false, 'Greasy and limp, batter slid right off.', ARRAY['soggy', 'greasy']::text[], '2026-09-14'),
  ((SELECT id FROM restaurants WHERE name = 'Mission Taqueria Luz'), 'Chile relleno burrito', 4, true, 'Smoky poblano, nice heat, salsa roja was great.', ARRAY['spicy', 'smoky']::text[], '2026-09-21'),
  ((SELECT id FROM restaurants WHERE name = 'Mission Taqueria Luz'), 'Chips and guac', 3, true, 'Chips were fresh and crispy but the guac needed salt and lime.', ARRAY['crispy', 'bland']::text[], '2026-09-21'),
  ((SELECT id FROM restaurants WHERE name = 'Bayou on Valencia'), 'Blackened catfish', 5, true, 'Peppery crust, flaky inside, perfect char. Order this.', ARRAY['charred', 'spicy', 'crispy']::text[], '2026-09-28'),
  ((SELECT id FROM restaurants WHERE name = 'Bayou on Valencia'), 'Beignets', 3, true, 'Hot and fluffy, a bit too much powdered sugar.', ARRAY['sweet']::text[], '2026-09-28'),
  ((SELECT id FROM restaurants WHERE name = 'Fog City Fish & Chips'), 'Beer-battered cod', 2, false, 'Batter went soft within minutes, greasy.', ARRAY['soggy', 'greasy']::text[], '2026-02-08'),
  ((SELECT id FROM restaurants WHERE name = 'Fog City Fish & Chips'), 'Fries', 3, true, 'Thick cut, decent crunch, needed salt.', ARRAY['crispy']::text[], '2026-02-08'),
  ((SELECT id FROM restaurants WHERE name = 'Fog City Fish & Chips'), 'Clam chowder', 2, false, 'Gluey and bland, hardly any clams.', ARRAY['bland']::text[], '2026-02-08'),
  ((SELECT id FROM restaurants WHERE name = 'Fog City Fish & Chips'), 'Fish tacos', 3, false, 'Fried fish limp again, slaw saved it.', ARRAY['soggy', 'tangy']::text[], '2026-06-12'),
  ((SELECT id FROM restaurants WHERE name = 'Noodle Cable Car'), 'Dan dan noodles', 5, true, 'Numbing heat, crispy pork, great chili oil.', ARRAY['spicy', 'crispy']::text[], '2026-03-02'),
  ((SELECT id FROM restaurants WHERE name = 'Noodle Cable Car'), 'Soup dumplings', 4, true, 'Thin skins, rich broth.', ARRAY['savory']::text[], '2026-03-02'),
  ((SELECT id FROM restaurants WHERE name = 'Noodle Cable Car'), 'Salt and pepper squid', 4, true, 'Shatteringly crisp and peppery.', ARRAY['crispy', 'peppery']::text[], '2026-03-02'),
  ((SELECT id FROM restaurants WHERE name = 'Noodle Cable Car'), 'Beef chow fun', 3, true, 'Good wok char but a touch oily.', ARRAY['charred', 'greasy']::text[], '2026-07-19'),
  ((SELECT id FROM restaurants WHERE name = 'Bernal Heights Barbecue Co.'), 'Brisket plate', 5, true, 'Peppery bark, smoke ring, fat rendered right.', ARRAY['smoky', 'peppery', 'hearty']::text[], '2026-04-11'),
  ((SELECT id FROM restaurants WHERE name = 'Bernal Heights Barbecue Co.'), 'Pulled pork sandwich', 3, false, 'Sauce swamped the bun, soggy by the last bite.', ARRAY['soggy', 'sweet']::text[], '2026-04-11'),
  ((SELECT id FROM restaurants WHERE name = 'Bernal Heights Barbecue Co.'), 'Burnt ends', 5, true, 'Charred, sticky, impossible to stop eating.', ARRAY['charred', 'smoky']::text[], '2026-08-23'),
  ((SELECT id FROM restaurants WHERE name = 'Bernal Heights Barbecue Co.'), 'Mac and cheese', 2, false, 'Gluey and bland, no crust on top.', ARRAY['bland']::text[], '2026-04-11'),
  ((SELECT id FROM restaurants WHERE name = 'Little Lotus Thai'), 'Pad thai', 2, false, 'Cloyingly sweet, noodles mushy.', ARRAY['sweet', 'soggy']::text[], '2026-01-25'),
  ((SELECT id FROM restaurants WHERE name = 'Little Lotus Thai'), 'Green curry', 4, true, 'Fragrant, properly hot, good eggplant.', ARRAY['spicy']::text[], '2026-01-25'),
  ((SELECT id FROM restaurants WHERE name = 'Little Lotus Thai'), 'Crispy pork belly basil', 5, true, 'Crackling skin, fiery, fried egg on top.', ARRAY['crispy', 'spicy']::text[], '2026-05-30'),
  ((SELECT id FROM restaurants WHERE name = 'Little Lotus Thai'), 'Mango sticky rice', 3, true, 'Pleasant but too sweet after the curry.', ARRAY['sweet']::text[], '2026-05-30'),
  ((SELECT id FROM restaurants WHERE name = 'The Salty Anchor'), 'Fried calamari', 2, false, 'Rubbery rings, heavy batter, way too salty.', ARRAY['salty', 'greasy']::text[], '2026-05-09'),
  ((SELECT id FROM restaurants WHERE name = 'The Salty Anchor'), 'Clam linguine', 3, false, 'Briny to the point of salty.', ARRAY['salty']::text[], '2026-05-09'),
  ((SELECT id FROM restaurants WHERE name = 'The Salty Anchor'), 'Oysters on the half shell', 4, true, 'Cold, clean, good mignonette.', ARRAY['briny']::text[], '2026-09-06'),
  ((SELECT id FROM restaurants WHERE name = 'The Salty Anchor'), 'Grilled octopus', 5, true, 'Charred tentacles, tender inside, smoky paprika.', ARRAY['charred', 'smoky']::text[], '2026-09-06'),
  ((SELECT id FROM restaurants WHERE name = 'Dolores Park Pizzeria'), 'Margherita', 4, true, 'Blistered crust, bright sauce.', ARRAY['charred', 'crispy']::text[], '2026-03-20'),
  ((SELECT id FROM restaurants WHERE name = 'Dolores Park Pizzeria'), 'Pepperoni and hot honey', 5, true, 'Cupped pepperoni, spicy honey, crisp edge.', ARRAY['spicy', 'crispy']::text[], '2026-03-20'),
  ((SELECT id FROM restaurants WHERE name = 'Dolores Park Pizzeria'), 'Garlic knots', 2, false, 'Doughy and oily, no garlic punch.', ARRAY['greasy', 'bland']::text[], '2026-03-20'),
  ((SELECT id FROM restaurants WHERE name = 'Dolores Park Pizzeria'), 'Caesar salad', 2, false, 'Limp romaine, bland dressing.', ARRAY['soggy', 'bland']::text[], '2026-08-02'),
  ((SELECT id FROM restaurants WHERE name = 'Sunset Sushi Studio'), 'Salmon nigiri', 4, true, 'Buttery fish, well-seasoned rice.', ARRAY['fresh']::text[], '2026-02-21'),
  ((SELECT id FROM restaurants WHERE name = 'Sunset Sushi Studio'), 'Spicy tuna roll', 3, true, 'Heat was fine, rice a bit mushy.', ARRAY['spicy', 'soggy']::text[], '2026-02-21'),
  ((SELECT id FROM restaurants WHERE name = 'Sunset Sushi Studio'), 'Tempura roll', 4, true, 'Crisp tempura, eel sauce not overdone.', ARRAY['crispy']::text[], '2026-06-27'),
  ((SELECT id FROM restaurants WHERE name = 'Sunset Sushi Studio'), 'Miso soup', 3, true, 'Fine, a little salty.', ARRAY['salty']::text[], '2026-06-27'),
  ((SELECT id FROM restaurants WHERE name = 'Calle Fuego'), 'Al pastor tacos', 5, true, 'Charred pineapple, crisp edges, pure heat.', ARRAY['charred', 'spicy', 'crispy']::text[], '2026-04-04'),
  ((SELECT id FROM restaurants WHERE name = 'Calle Fuego'), 'Birria quesadilla', 4, true, 'Crisp cheese skirt, rich consome.', ARRAY['crispy', 'hearty']::text[], '2026-04-04'),
  ((SELECT id FROM restaurants WHERE name = 'Calle Fuego'), 'Elote', 4, true, 'Smoky char, cotija, lime.', ARRAY['charred', 'smoky']::text[], '2026-09-18'),
  ((SELECT id FROM restaurants WHERE name = 'Calle Fuego'), 'Chips and guac', 2, false, 'Stale chips, guac browned and bland.', ARRAY['bland']::text[], '2026-09-18'),
  ((SELECT id FROM restaurants WHERE name = 'Nob Hill Steakhouse'), 'Ribeye', 5, true, 'Proper sear, medium-rare, peppery crust.', ARRAY['charred', 'peppery', 'hearty']::text[], '2026-07-04'),
  ((SELECT id FROM restaurants WHERE name = 'Nob Hill Steakhouse'), 'Wedge salad', 3, true, 'Crisp lettuce, good bacon, dressing heavy.', ARRAY['crispy']::text[], '2026-07-04'),
  ((SELECT id FROM restaurants WHERE name = 'Nob Hill Steakhouse'), 'French onion soup', 2, false, 'Cheese cap went soggy, broth too salty.', ARRAY['soggy', 'salty']::text[], '2026-07-04'),
  ((SELECT id FROM restaurants WHERE name = 'Nob Hill Steakhouse'), 'Creamed spinach', 2, false, 'Bland and watery.', ARRAY['bland']::text[], '2026-07-04'),
  ((SELECT id FROM restaurants WHERE name = 'Presidio Picnic Cafe'), 'Turkey avocado sandwich', 3, true, 'Fresh but nothing special.', ARRAY['bland']::text[], '2026-05-17'),
  ((SELECT id FROM restaurants WHERE name = 'Presidio Picnic Cafe'), 'Chicken salad croissant', 2, false, 'Soggy croissant, mayo-heavy.', ARRAY['soggy']::text[], '2026-05-17'),
  ((SELECT id FROM restaurants WHERE name = 'Presidio Picnic Cafe'), 'Tomato soup with grilled cheese', 4, true, 'Crisp buttery bread, silky soup.', ARRAY['crispy']::text[], '2026-10-01'),
  ((SELECT id FROM restaurants WHERE name = 'Presidio Picnic Cafe'), 'Lemon bar', 3, true, 'Tart with good shortbread.', ARRAY['sweet']::text[], '2026-10-01'),
  ((SELECT id FROM restaurants WHERE name = 'Marina Brunch Club'), 'Chicken and waffles', 5, true, 'Crackling fried chicken, hot sauce, waffle held up.', ARRAY['crispy', 'spicy']::text[], '2026-08-15'),
  ((SELECT id FROM restaurants WHERE name = 'Marina Brunch Club'), 'Eggs benedict', 2, false, 'Hollandaise broke, English muffin soggy.', ARRAY['soggy']::text[], '2026-08-15'),
  ((SELECT id FROM restaurants WHERE name = 'Marina Brunch Club'), 'Chilaquiles', 4, true, 'Crisp chips in salsa, fried egg on top.', ARRAY['crispy', 'spicy']::text[], '2026-09-27'),
  ((SELECT id FROM restaurants WHERE name = 'Marina Brunch Club'), 'Avocado toast', 3, true, 'Thick toast, under-seasoned.', ARRAY['bland']::text[], '2026-09-27'),
  ((SELECT id FROM restaurants WHERE name = 'Hayes Valley Ramen Bar'), 'Tonkotsu ramen', 4, true, 'Rich broth, perfect noodles.', ARRAY['hearty']::text[], '2026-01-18'),
  ((SELECT id FROM restaurants WHERE name = 'Hayes Valley Ramen Bar'), 'Spicy miso ramen', 5, true, 'Fiery, chewy noodles, charred corn.', ARRAY['spicy', 'charred']::text[], '2026-01-18'),
  ((SELECT id FROM restaurants WHERE name = 'Hayes Valley Ramen Bar'), 'Gyoza', 3, true, 'Crisp bottoms, filling a bit bland.', ARRAY['crispy']::text[], '2026-07-30'),
  ((SELECT id FROM restaurants WHERE name = 'Hayes Valley Ramen Bar'), 'Karaage', 4, true, 'Crunchy, juicy, not greasy.', ARRAY['crispy']::text[], '2026-07-30'),
  ((SELECT id FROM restaurants WHERE name = 'Bayou on Valencia'), 'Jambalaya', 4, true, 'Smoky andouille, rice with a crisp crust.', ARRAY['smoky', 'spicy']::text[], '2026-10-03'),
  ((SELECT id FROM restaurants WHERE name = 'Golden Gate Grill'), 'Clam chowder', 2, false, 'Salty and gluey.', ARRAY['salty']::text[], '2026-10-02');
